/****************************************************************************/
/*                                SCANER.H                                  */
/****************************************************************************/

void busca_archivos(unsigned char unidad);
void busca(unsigned char unidad);
int lee_numser(unsigned char unidad);
int graba_numser(unsigned char unidad,unsigned numdisco);
